// Code generated by protoc-gen-go. DO NOT EDIT.
// source: caseylucas/first/v1/first_api.proto

package firstv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf357b53ce16c1, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf357b53ce16c1, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "caseylucas.first.v1.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "caseylucas.first.v1.EchoResponse")
}

func init() {
	proto.RegisterFile("caseylucas/first/v1/first_api.proto", fileDescriptor_98cf357b53ce16c1)
}

var fileDescriptor_98cf357b53ce16c1 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x4e, 0x2c, 0x4e,
	0xad, 0xcc, 0x29, 0x4d, 0x4e, 0x2c, 0xd6, 0x4f, 0xcb, 0x2c, 0x2a, 0x2e, 0xd1, 0x2f, 0x33, 0x84,
	0x30, 0xe2, 0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0x11, 0x8a, 0xf4,
	0xc0, 0x72, 0x7a, 0x65, 0x86, 0x4a, 0xea, 0x5c, 0xdc, 0xae, 0xc9, 0x19, 0xf9, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x06, 0x17, 0x0f, 0x44, 0x61, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0x2a, 0x6e, 0x95, 0x46, 0xe1, 0x5c, 0x1c, 0x6e, 0x20, 0xe3, 0x1d, 0x03, 0x3c,
	0x85, 0xbc, 0xb9, 0x58, 0x40, 0xba, 0x84, 0x14, 0xf4, 0xb0, 0x58, 0xae, 0x87, 0x64, 0xb3, 0x94,
	0x22, 0x1e, 0x15, 0x10, 0x2b, 0x9d, 0x52, 0xb9, 0xc4, 0x93, 0xf3, 0x73, 0xb1, 0xa9, 0x73, 0xe2,
	0x85, 0xd8, 0x58, 0x90, 0x19, 0x00, 0xf2, 0x6a, 0x00, 0x63, 0x14, 0x3b, 0x58, 0xaa, 0xcc, 0x70,
	0x11, 0x13, 0xb3, 0xb3, 0x5b, 0xc4, 0x2a, 0x26, 0x61, 0x67, 0x84, 0x2e, 0xb0, 0x5a, 0xbd, 0x30,
	0xc3, 0x53, 0xc8, 0xa2, 0x31, 0x60, 0xd1, 0x98, 0x30, 0xc3, 0x24, 0x36, 0x70, 0x70, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x18, 0x0c, 0x26, 0xdd, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FirstAPIClient is the client API for FirstAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FirstAPIClient interface {
	// Echo returns the passed message.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type firstAPIClient struct {
	cc *grpc.ClientConn
}

func NewFirstAPIClient(cc *grpc.ClientConn) FirstAPIClient {
	return &firstAPIClient{cc}
}

func (c *firstAPIClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/caseylucas.first.v1.FirstAPI/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstAPIServer is the server API for FirstAPI service.
type FirstAPIServer interface {
	// Echo returns the passed message.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterFirstAPIServer(s *grpc.Server, srv FirstAPIServer) {
	s.RegisterService(&_FirstAPI_serviceDesc, srv)
}

func _FirstAPI_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstAPIServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caseylucas.first.v1.FirstAPI/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstAPIServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FirstAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "caseylucas.first.v1.FirstAPI",
	HandlerType: (*FirstAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _FirstAPI_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "caseylucas/first/v1/first_api.proto",
}
